### ISSUE TITLE
Enable API-Wrapper to check multiple Authorization Header

### ISSUE THREAD

**Issue by florianrusch-zf** [catenax-ng/catenax-at-home#31]
## Describe the bug
Currently, the api-wrapper checks only the first `Authorization` header value if it matches a configured basic auth user.

### To Reproduce
Try to send multiple `Authorization` header, where the second is the correct one for the wrapper.

### Expected behavior
The wrapper should check all `Authorization` header for a correct credential.

## Possible Implementation
Maybe we can reuse the following edc module: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/api/auth-basic

**Comment by matgnt** [comment]
Does this cause the following `api-wrapper` error message?
```
getting-started-guide-api-wrapper-1  | Caused by: java.lang.IllegalArgumentException: Illegal base64 character 2e
getting-started-guide-api-wrapper-1  |  at java.base/java.util.Base64$Decoder.decode0(Unknown Source)
getting-started-guide-api-wrapper-1  |  at java.base/java.util.Base64$Decoder.decode(Unknown Source)
getting-started-guide-api-wrapper-1  |  at java.base/java.util.Base64$Decoder.decode(Unknown Source)
getting-started-guide-api-wrapper-1  |  at org.eclipse.dataspaceconnector.apiwrapper.security.BasicAuthenticationService.isAuthenticated(BasicAuthenticationService.java:37)
getting-started-guide-api-wrapper-1  |  at org.eclipse.dataspaceconnector.api.auth.AuthenticationRequestFilter.filter(AuthenticationRequestFilter.java:35)

```

**Comment by matgnt** [comment]
Ignore my message. I used the registry bearer token at the api wrapper API instead of the basic auth it expects. That was causing the error :-)
