### ISSUE TITLE
AAS-Proxy removes 'semanticId' field from the submodelDescriptors

### ISSUE THREAD

**Issue by matgnt** [catenax-ng/catenax-at-home#46]
image: ghcr.io/catenax-ng/catenax-at-home/consumer-aas-proxy-service:0.0.1
(used in getting-started-guide distributed)

Querying an AAS via the aas-proxy returns the list of `submodelDescriptors` without the field `semanticId`.
If I query the registry directly, the field is there.

This is a problem because the value is used to determine which endpoint to fetch the data from.

@florianrusch-zf @stefan-ettl Can someone confirm?
It's blocking our testing efforts

**Comment by florianrusch-zf** [comment]
@matgnt thanks for reporting this.

I directly create a defect in the Catena-X Jira for the EDC Team: https://jira.catena-x.net/browse/A1IDSC-144
There was also a question within Confluence regarding this: https://confluence.catena-x.net/display/CORE/Asset+Administration+Shell+Services+and+API+Profiles+for+CATENA-X?focusedCommentId=39814210#comment-39814210
