### ISSUE TITLE
Missing rename of api-wrapper

### ISSUE THREAD

**Issue by dblankevia** [catenax-ng/catenax-at-home#61]
## Describe the bug
When building and running the containers locally via `api-wrapper/docker-compose.yml`, aas-proxy tries to reach api-wrapper using the hostname `api-wrapper` instead of the new `consumer-api-wrapper`.

## Possible Implementation
Change the default URL in api-wrapper/services/semantics/aasproxy/Dockerfile:7 to
```
ENV AASPROXY_WRAPPERURL http://consumer-api-wrapper:9191/api/service
```

**Comment by florianrusch-zf** [comment]
@dblankevia Good catch! Fixed it in a other way to prevent having a new release
